package com.lindacare.studentgrade.model;

public enum SubjectCode {
	AAD, AAAP, ACTG, AEIS, AFR, AIM, ANTH, ARB, ARCH, ARH, ART, ARTC, ARTD, ARTF,
    ARTM, ARTO, ARTP, ARTR, ARTS, ASIA, ASL, ASTR, BA, BE, BI, CAS, CDS, CFT, CH,
    CHN, CINE, CIS, CIT, CLAS, COLT, CPSY, CRES, CRWR, DAN, DANC, DANE, DSGN, EALL,
    EC, EDLD, EDST, EDUC, ENG, ENVS, ES, EURO, FHS, FIN, FINN, FLR, FR, GEOG, GEOL,
    GER, GRK, GRST, GSS, HBRW, HC, HIST, HPHY, HUM, IARC, INTL, IST, ITAL, J, JDST,
    JPN, KRN, LA, LAS, LAT, LAW, LERC, LIB, LING, LT, MATH, MDVL, MGMT, MIL, MKTG,
    MUE, MUJ, MUP, MUS, NORW, OBA, OLIS, PD, PEAE, PEAQ, PEAS, PEC, PEF, PEI, PEIA,
    PEL, PEMA, PEMB, PEO, PERS, PERU, PETS, PEW, PHIL, PHYS, PORT, PPPM, PREV, PS,
    PSY, REES, REL, RL, RUSS, SBUS, SCAN, SOC, SPAN, SPD, SPED, SPSY, SWAH, SWED,
    TA, TLC, UGST, WGS, WR, OAKI, OANG, OANU, OATH, OBEI, OBER, OBIK, OBLN, OBRI,
    OBRT, OBWU, OCAM, OCBS, OCFP, OCIE, OCRO, OCUB, OCUR, ODEA, ODIS, ODUB, OESL,
    OEWH, OFES, OFIB, OGAL, OGBS, OGHA, OHAR, OHAU, OHKU, OHOU, OHUJ, OHUM, OINT,
    OJCU, OJIL, OJWU, OKYO, OLAT, OLEC, OLEI, OLON, OLYO, OMBI, OMEI, OMKT, ONEO,
    ONTU, ONUI, ONUS, OOVI, OPAV, OPAY, OPOI, OQUE, OQUI, OROM, OROS, OSAS, OSCI,
    OSEG, OSEN, OSIE, OSIP, OSIT, OSLO, OSSP, OTAM, OTSP, OUAB, OUDB, OUDL, OUEA,
    OUNA, OUOT, OUPP, OVAN, OVIC, OVIE, OVLC, OWAS, OXAF, OXAO, OXEU, OXFA, OXLA,
    OXME, OYON
}
